-- Switches login/registration from email to legajo (employee ID number).
-- Supabase Auth still requires an email internally for auth.users, so each
-- profile keeps a synthetic, non-deliverable email (legajo@legajo.mantia.internal)
-- generated by the invite-user Edge Function — it's never shown or collected
-- in the UI anymore, only `legajo` is.

alter table profiles add column legajo text unique;

-- Nullable on purpose: existing rows (created before this migration) have no
-- legajo yet and must be backfilled by hand — see supabase/SETUP.md. New
-- rows always get one; both the invite-user Edge Function and this check
-- enforce it going forward.
alter table profiles add constraint profiles_legajo_digits_chk
  check (legajo is null or legajo ~ '^[0-9]+$');

-- Looks up the synthetic auth email for a given legajo so the login screen
-- can resolve legajo -> email before calling signInWithPassword (Supabase
-- Auth itself only ever authenticates by email/password). security definer
-- + granted to anon because this must run before the user has a session;
-- it only ever returns the synthetic email string, never anything else off
-- profiles, so it's safe to expose pre-auth.
create function email_for_legajo(p_legajo text) returns text
language sql stable security definer
set search_path = public
as $$
  select email from profiles where legajo = p_legajo
$$;

grant execute on function email_for_legajo(text) to anon, authenticated;
